
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Anatomy and Physiology'
tagline:          'from http://cnx.org/contents/14fb4ad7-39a1-4eee-ab6e-3ef2482e3e22@8.119 (CC-BY)'
url:              https://github.com/philschatz/anatomy-book
origin:           http://cnx.org/contents/14fb4ad7-39a1-4eee-ab6e-3ef2482e3e22@8.119

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          8.119

bookviewer:       http://philschatz.com/book-viewer

